import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Image } from "@/components/ui/image";
import { Archive, ChevronDown, Package, Pause, Play, Plus, Search } from "lucide-react";
import { formatCurrency, formatNumber } from "@/lib/treebay";

export default function SellerInventory({ vendorIds }) {
  const [products, setProducts] = useState([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState("all"); const [sort, setSort] = useState("newest"); const [low, setLow] = useState(false);
  const load = () => Promise.all(vendorIds.map((vendor_id) => base44.entities.Product.filter({ vendor_id }, "-created_date", 100))).then((lists) => setProducts(lists.flat()));
  useEffect(() => { load(); }, [vendorIds.join(",")]);
  const visible = useMemo(() => products.filter((p) => (!search || `${p.common_name} ${p.category}`.toLowerCase().includes(search.toLowerCase())) && (status === "all" || p.listing_status === status) && (!low || (p.quantity_available > 0 && p.quantity_available <= 5))).sort((a, b) => sort === "price" ? a.unit_price - b.unit_price : sort === "stock" ? b.quantity_available - a.quantity_available : new Date(b.created_date) - new Date(a.created_date)), [products, search, status, sort, low]);
  const update = async (product, listing_status) => { await base44.functions.invoke("updateProduct", { productId: product.id, listing_status }); load(); };
  return <div className="space-y-5"><header className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">Seller inventory</p><h1 className="font-heading text-2xl font-bold">Inventory</h1><p className="text-sm text-muted-foreground">Physical stock is what you own; reserved is held for active orders; available is ready for new orders.</p></div><Button asChild className="min-h-11"><Link to="/vendor/inventory/new"><Plus className="w-4 h-4" /> Add Product</Link></Button></header><div className="grid gap-2 md:grid-cols-4"><div className="relative md:col-span-2"><Search className="absolute left-3 top-3 w-4 h-4 text-muted-foreground" /><Input value={search} onChange={(e) => setSearch(e.target.value)} className="h-11 pl-9" placeholder="Search inventory" /></div><Select value={status} onValueChange={setStatus}><SelectTrigger className="h-11"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem><SelectItem value="active">Active</SelectItem><SelectItem value="paused">Paused</SelectItem><SelectItem value="sold_out">Sold out</SelectItem><SelectItem value="archived">Archived</SelectItem></SelectContent></Select><Select value={sort} onValueChange={setSort}><SelectTrigger className="h-11"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="newest">Newest</SelectItem><SelectItem value="price">Price</SelectItem><SelectItem value="stock">Available stock</SelectItem></SelectContent></Select></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={low} onChange={(e) => setLow(e.target.checked)} /> Low stock only</label>{visible.length ? <><div className="hidden md:block overflow-hidden rounded-xl border"><table className="w-full text-sm"><thead className="bg-secondary/60 text-left text-xs text-muted-foreground"><tr><th className="p-3">Product</th><th>Size</th><th>PHYSICAL</th><th>RESERVED</th><th>AVAILABLE</th><th>SOLD</th><th>Price</th><th>Status</th><th /></tr></thead><tbody>{visible.map((p) => <InventoryRow key={p.id} p={p} update={update} />)}</tbody></table></div><div className="md:hidden space-y-3">{visible.map((p) => <InventoryCard key={p.id} p={p} update={update} />)}</div></> : <Card className="p-8 text-center"><Package className="mx-auto text-primary" /><h2 className="mt-3 font-semibold">No inventory found</h2><p className="mt-1 text-sm text-muted-foreground">Your inventory is empty. Add your first product to start showing buyers what you grow.</p><Button asChild className="mt-4"><Link to="/vendor/inventory/new">Add Product</Link></Button></Card>}</div>;
}
function Actions({ p, update }) { return <div className="flex gap-1"><Button variant="ghost" size="sm" asChild><Link to={`/vendor/inventory/${p.id}`}>Edit</Link></Button>{p.listing_status === "active" ? <Button variant="ghost" size="icon" aria-label="Pause listing" onClick={() => update(p, "paused")}><Pause className="w-4 h-4" /></Button> : <Button variant="ghost" size="icon" aria-label="Activate listing" onClick={() => update(p, "active")}><Play className="w-4 h-4" /></Button>}<Button variant="ghost" size="icon" aria-label="Archive listing" onClick={() => update(p, "archived")}><Archive className="w-4 h-4" /></Button></div>; }
function InventoryRow({ p, update }) { return <tr className="border-t"><td className="p-3"><Link to={`/vendor/inventory/${p.id}`} className="flex items-center gap-3 font-semibold">{p.images?.[0] && <Image src={p.images[0]} alt={p.common_name} className="h-10 w-10 rounded-md" />} {p.common_name}</Link></td><td>{p.container_size || p.caliper || "—"}</td><td>{formatNumber(p.physical_quantity ?? 0)}</td><td>{formatNumber(p.quantity_reserved ?? 0)}</td><td className="font-semibold">{formatNumber(p.quantity_available)}</td><td>{formatNumber(p.quantity_sold ?? 0)}</td><td>{formatCurrency(p.unit_price)}</td><td><span className="text-xs">{p.listing_status.replaceAll("_", " ")}</span></td><td><Actions p={p} update={update} /></td></tr>; }
function InventoryCard({ p, update }) { return <Card className="p-3"><div className="flex gap-3"><div className="h-16 w-16 overflow-hidden rounded-lg bg-secondary">{p.images?.[0] && <Image src={p.images[0]} alt={p.common_name} className="h-full w-full" />}</div><div className="flex-1"><p className="font-semibold">{p.common_name}</p><p className="text-xs text-muted-foreground">{p.container_size || p.caliper || "Size not specified"} · {formatCurrency(p.unit_price)}</p><div className="mt-2 grid grid-cols-3 text-xs"><span>Physical<b className="block">{formatNumber(p.physical_quantity ?? 0)}</b></span><span>Reserved<b className="block">{formatNumber(p.quantity_reserved ?? 0)}</b></span><span>Available<b className="block">{formatNumber(p.quantity_available)}</b></span></div></div></div><div className="mt-3 flex items-center justify-between"><span className="text-xs font-medium">{p.listing_status.replaceAll("_", " ")}</span><Actions p={p} update={update} /></div></Card>; }